#!/bin/bash
# WF 2018-08-22
# regenerate BITPlan Open Source list
checkos -a
# regenerate the README of this project
checkos -w https://github.com/BITPlan/com.bitplan.pom/blob/master/docs/BITPlanOSProjects.md -p com.bitplan.pom 

